# Generated by Django 5.1.7 on 2025-03-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=21, verbose_name='cantidad en stok'),
        ),
    ]
