# Generated by Django 5.1.7 on 2025-03-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_inventario_cant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cant',
            field=models.IntegerField(default=0, verbose_name='cantidad en stok'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio del producto'),
        ),
    ]
